---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: server_arm64:latest
          env:
          - name: REDIS_URL
            value: redis://redis:6379/
          resources:
            requests:
              cpu: 500m
              memory: 1000Mi
            limits:
              cpu: 1000m
              memory: 2000Mi
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000

      initContainers:
        - name: init-verify-redis-service-dns
          image: busybox:1.28
          command:
            [
              "sh",
              "-c",
              "until nc -vz redis 6379; do echo 'waiting for redis service from DNS'; sleep 2; done",
            ]
        - name: init-verify-redis-ready
          image: busybox:1.28
          command:
            [
              "sh",
              "-c",
              "until (printf 'PING\r\n';) | nc redis 6379; do echo 'waiting for redis to PONG'; sleep 1; done",
            ]
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: server
  minReplicas: 1
  maxReplicas: 40
  targetCPUUtilizationPercentage: 50
