---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: caopuzheng
resources:
  - ../../base
  - virtual-service.yaml
patches:
  - path: patch-deployment-server.yaml
    target:
      kind: Deployment
      labelSelector: "app=server"
