---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: server
spec:
  hosts:
    - caopuzheng.mids255.com
  gateways:
    - istio-ingress/caopuzheng-gateway
  http:
    - match:
        - uri:
            exact: /baseline_allocate
        - uri:
            exact: /ml_allocate_embeddings
        - uri:
            exact: /ml_allocate_cosine_similarity    
        - uri:
            prefix: /hello
        - uri:
            prefix: /health
        - uri:
            prefix: /docs
        - uri:
            prefix: /openapi.json
      route:
        - destination:
            host: server
            port:
              number: 8000
